version: 0.2

phases:
    install:
        commands:
            - pip install Pygments
            - wget https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.deb
            - dpkg -i hugo_0.51_Linux-64bit.deb
    build:
        commands:
            - git submodule update --init --recursive
            - hugo
            - echo "S3 Upload Beginning"
            - aws s3 sync public/ s3://randall.bot/ --region us-east-1 --delete --sse AES256
            - echo "S3 Upload Complete"
    post_build:
        commands:
            - echo "Build complete"
